apiVersion: v1
kind: Pod
metadata:
  name: master-nginx
  labels:
    name: master-nginx
spec:
  containers:
  - name: master-nginx
    image: nilamballal169/cloudethix_master_nginx_nilam:v1
    ports:
      - containerPort: 80
